services:
  proxy:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    environment:
      APPNAME: Admin
      APPURL: ${APPURL:-https://1pc.tf:8080}
      APPURLREGEX: ^http(s|)://.*$
      APPSECRET: FINDIT{134k_f0r_s3cr3t}
      APPLIMIT: 2
      APPLIMITTIME: 60
      USE_PROXY: 1
      # DISPLAY: ${DISPLAY}
    # volumes:
      # - /tmp/.X11-unix:/tmp/.X11-unix
