services:
  kopi_naught_fail:
    build: .
    restart: on-failure
    ports:
      - 31431:31431
    deploy:
      resources:
        limits:
          cpus: 1.0
          memory: 512m
        reservations:
          cpus: 1.0
          memory: 512m