services:
  kopi_naught_fail:
    build: .
    restart: on-failure
    ports:
      - 31431:31431
    deploy:
      resources:
        limits:
          cpus: "1.5"
          memory: "512M"
        reservations:
          cpus: "0.5"
          memory: "256M"