services:
  tower_of_babel:
    build: .
    restart: on-failure
    ports:
      - 1094:1094
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "512M"
        reservations:
          cpus: "0.5"
          memory: "256M"
